version: "3.8"
services:
  app:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - DATABASE_URL=sqlite:///app/data/app.db
      - SEED_ON_START=true
    restart: unless-stopped
